exec-once=paplay ~/.config/hypr/config.d/sounds/Windows_11.wav
exec-once=awww-daemon
exec-once=hyprctl setcursor Banana-Dracula 64
exec-once=waybar
exec-once=copyq --start-server
exec-once=dunst
exec-once=hypridle
exec-once=syncthing --no-browser
exec=gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
